// Code generated by protoc-gen-go.
// source: timeline.proto
// DO NOT EDIT!

/*
Package timeline is a generated protocol buffer package.

It is generated from these files:
	timeline.proto

It has these top-level messages:
	TimelineRequest
	TimelineReport
	UpdateDetail
	Score
*/
package timeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateType int32

const (
	UpdateType_KickOff           UpdateType = 0
	UpdateType_Goal              UpdateType = 1
	UpdateType_YellowCard        UpdateType = 2
	UpdateType_RedCard           UpdateType = 3
	UpdateType_FirstHalfEnd      UpdateType = 4
	UpdateType_SecondHalfEnd     UpdateType = 5
	UpdateType_SecondHalfKickOff UpdateType = 6
	UpdateType_MissedPenalty     UpdateType = 7
	UpdateType_Penalties         UpdateType = 8
)

var UpdateType_name = map[int32]string{
	0: "KickOff",
	1: "Goal",
	2: "YellowCard",
	3: "RedCard",
	4: "FirstHalfEnd",
	5: "SecondHalfEnd",
	6: "SecondHalfKickOff",
	7: "MissedPenalty",
	8: "Penalties",
}
var UpdateType_value = map[string]int32{
	"KickOff":           0,
	"Goal":              1,
	"YellowCard":        2,
	"RedCard":           3,
	"FirstHalfEnd":      4,
	"SecondHalfEnd":     5,
	"SecondHalfKickOff": 6,
	"MissedPenalty":     7,
	"Penalties":         8,
}

func (x UpdateType) String() string {
	return proto.EnumName(UpdateType_name, int32(x))
}
func (UpdateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TimelineReport_Status int32

const (
	TimelineReport_IN_PLAY  TimelineReport_Status = 0
	TimelineReport_COMPLETE TimelineReport_Status = 1
)

var TimelineReport_Status_name = map[int32]string{
	0: "IN_PLAY",
	1: "COMPLETE",
}
var TimelineReport_Status_value = map[string]int32{
	"IN_PLAY":  0,
	"COMPLETE": 1,
}

func (x TimelineReport_Status) String() string {
	return proto.EnumName(TimelineReport_Status_name, int32(x))
}
func (TimelineReport_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type UpdateDetail_Team int32

const (
	UpdateDetail_home UpdateDetail_Team = 0
	UpdateDetail_away UpdateDetail_Team = 1
)

var UpdateDetail_Team_name = map[int32]string{
	0: "home",
	1: "away",
}
var UpdateDetail_Team_value = map[string]int32{
	"home": 0,
	"away": 1,
}

func (x UpdateDetail_Team) String() string {
	return proto.EnumName(UpdateDetail_Team_name, int32(x))
}
func (UpdateDetail_Team) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type TimelineRequest struct {
	EventId uint64 `protobuf:"varint,1,opt,name=eventId" json:"eventId,omitempty"`
}

func (m *TimelineRequest) Reset()                    { *m = TimelineRequest{} }
func (m *TimelineRequest) String() string            { return proto.CompactTextString(m) }
func (*TimelineRequest) ProtoMessage()               {}
func (*TimelineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TimelineReport struct {
	EventTypeId        uint32                `protobuf:"varint,1,opt,name=eventTypeId" json:"eventTypeId,omitempty"`
	EventId            uint64                `protobuf:"varint,2,opt,name=eventId" json:"eventId,omitempty"`
	Score              *Score                `protobuf:"bytes,3,opt,name=score" json:"score,omitempty"`
	TimeElapsed        int32                 `protobuf:"varint,4,opt,name=timeElapsed" json:"timeElapsed,omitempty"`
	ElapsedRegularTime int32                 `protobuf:"varint,5,opt,name=elapsedRegularTime" json:"elapsedRegularTime,omitempty"`
	UpdateDetails      []*UpdateDetail       `protobuf:"bytes,6,rep,name=updateDetails" json:"updateDetails,omitempty"`
	Status             TimelineReport_Status `protobuf:"varint,7,opt,name=status,enum=timeline.TimelineReport_Status" json:"status,omitempty"`
	InPlayMatchStatus  UpdateType            `protobuf:"varint,8,opt,name=inPlayMatchStatus,enum=timeline.UpdateType" json:"inPlayMatchStatus,omitempty"`
}

func (m *TimelineReport) Reset()                    { *m = TimelineReport{} }
func (m *TimelineReport) String() string            { return proto.CompactTextString(m) }
func (*TimelineReport) ProtoMessage()               {}
func (*TimelineReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimelineReport) GetScore() *Score {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *TimelineReport) GetUpdateDetails() []*UpdateDetail {
	if m != nil {
		return m.UpdateDetails
	}
	return nil
}

type TimelineReport_FullTimeElapsed struct {
	Hour int32 `protobuf:"varint,1,opt,name=hour" json:"hour,omitempty"`
	Min  int32 `protobuf:"varint,2,opt,name=min" json:"min,omitempty"`
	Sec  int32 `protobuf:"varint,3,opt,name=sec" json:"sec,omitempty"`
}

func (m *TimelineReport_FullTimeElapsed) Reset()         { *m = TimelineReport_FullTimeElapsed{} }
func (m *TimelineReport_FullTimeElapsed) String() string { return proto.CompactTextString(m) }
func (*TimelineReport_FullTimeElapsed) ProtoMessage()    {}
func (*TimelineReport_FullTimeElapsed) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type UpdateDetail struct {
	UpdateTime         *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=updateTime" json:"updateTime,omitempty"`
	UpdateId           int32                      `protobuf:"varint,2,opt,name=updateId" json:"updateId,omitempty"`
	Team               UpdateDetail_Team          `protobuf:"varint,3,opt,name=team,enum=timeline.UpdateDetail_Team" json:"team,omitempty"`
	TeamName           string                     `protobuf:"bytes,4,opt,name=teamName" json:"teamName,omitempty"`
	MatchTime          int32                      `protobuf:"varint,5,opt,name=matchTime" json:"matchTime,omitempty"`
	ElapsedRegularTime int32                      `protobuf:"varint,6,opt,name=elapsedRegularTime" json:"elapsedRegularTime,omitempty"`
	Type               UpdateType                 `protobuf:"varint,7,opt,name=type,enum=timeline.UpdateType" json:"type,omitempty"`
	UpdateType         UpdateType                 `protobuf:"varint,8,opt,name=updateType,enum=timeline.UpdateType" json:"updateType,omitempty"`
	ElapsedAddedTime   int32                      `protobuf:"varint,9,opt,name=elapsedAddedTime" json:"elapsedAddedTime,omitempty"`
}

func (m *UpdateDetail) Reset()                    { *m = UpdateDetail{} }
func (m *UpdateDetail) String() string            { return proto.CompactTextString(m) }
func (*UpdateDetail) ProtoMessage()               {}
func (*UpdateDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateDetail) GetUpdateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Score struct {
	Home                      *Score_ScoreDetail `protobuf:"bytes,1,opt,name=home" json:"home,omitempty"`
	Away                      *Score_ScoreDetail `protobuf:"bytes,2,opt,name=away" json:"away,omitempty"`
	NumberOfYellowCards       int32              `protobuf:"varint,3,opt,name=numberOfYellowCards" json:"numberOfYellowCards,omitempty"`
	NumberOfRedCards          int32              `protobuf:"varint,4,opt,name=numberOfRedCards" json:"numberOfRedCards,omitempty"`
	NumberOfCards             int32              `protobuf:"varint,5,opt,name=numberOfCards" json:"numberOfCards,omitempty"`
	NumberOfCorners           int32              `protobuf:"varint,6,opt,name=numberOfCorners" json:"numberOfCorners,omitempty"`
	NumberOfCornersFirstHalf  int32              `protobuf:"varint,7,opt,name=numberOfCornersFirstHalf" json:"numberOfCornersFirstHalf,omitempty"`
	NumberOfCornersSecondHalf int32              `protobuf:"varint,8,opt,name=numberOfCornersSecondHalf" json:"numberOfCornersSecondHalf,omitempty"`
	BookingPoints             int32              `protobuf:"varint,9,opt,name=bookingPoints" json:"bookingPoints,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Score) GetHome() *Score_ScoreDetail {
	if m != nil {
		return m.Home
	}
	return nil
}

func (m *Score) GetAway() *Score_ScoreDetail {
	if m != nil {
		return m.Away
	}
	return nil
}

type Score_ScoreDetail struct {
	Name                      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Score                     string   `protobuf:"bytes,2,opt,name=score" json:"score,omitempty"`
	HalfTimeScore             string   `protobuf:"bytes,3,opt,name=halfTimeScore" json:"halfTimeScore,omitempty"`
	FullTimeScore             string   `protobuf:"bytes,4,opt,name=fullTimeScore" json:"fullTimeScore,omitempty"`
	PenaltiesScore            string   `protobuf:"bytes,5,opt,name=penaltiesScore" json:"penaltiesScore,omitempty"`
	PenaltiesSequence         []string `protobuf:"bytes,6,rep,name=penaltiesSequence" json:"penaltiesSequence,omitempty"`
	Games                     string   `protobuf:"bytes,7,opt,name=games" json:"games,omitempty"`
	Sets                      string   `protobuf:"bytes,8,opt,name=sets" json:"sets,omitempty"`
	NumberOfYellowCards       int32    `protobuf:"varint,9,opt,name=numberOfYellowCards" json:"numberOfYellowCards,omitempty"`
	NumberOfRedCards          int32    `protobuf:"varint,10,opt,name=numberOfRedCards" json:"numberOfRedCards,omitempty"`
	NumberOfCards             int32    `protobuf:"varint,11,opt,name=numberOfCards" json:"numberOfCards,omitempty"`
	NumberOfCorners           int32    `protobuf:"varint,12,opt,name=numberOfCorners" json:"numberOfCorners,omitempty"`
	NumberOfCornersFirstHalf  int32    `protobuf:"varint,13,opt,name=numberOfCornersFirstHalf" json:"numberOfCornersFirstHalf,omitempty"`
	NumberOfCornersSecondHalf int32    `protobuf:"varint,14,opt,name=numberOfCornersSecondHalf" json:"numberOfCornersSecondHalf,omitempty"`
	BookingPoints             int32    `protobuf:"varint,15,opt,name=bookingPoints" json:"bookingPoints,omitempty"`
}

func (m *Score_ScoreDetail) Reset()                    { *m = Score_ScoreDetail{} }
func (m *Score_ScoreDetail) String() string            { return proto.CompactTextString(m) }
func (*Score_ScoreDetail) ProtoMessage()               {}
func (*Score_ScoreDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func init() {
	proto.RegisterType((*TimelineRequest)(nil), "timeline.TimelineRequest")
	proto.RegisterType((*TimelineReport)(nil), "timeline.TimelineReport")
	proto.RegisterType((*TimelineReport_FullTimeElapsed)(nil), "timeline.TimelineReport.FullTimeElapsed")
	proto.RegisterType((*UpdateDetail)(nil), "timeline.UpdateDetail")
	proto.RegisterType((*Score)(nil), "timeline.Score")
	proto.RegisterType((*Score_ScoreDetail)(nil), "timeline.Score.ScoreDetail")
	proto.RegisterEnum("timeline.UpdateType", UpdateType_name, UpdateType_value)
	proto.RegisterEnum("timeline.TimelineReport_Status", TimelineReport_Status_name, TimelineReport_Status_value)
	proto.RegisterEnum("timeline.UpdateDetail_Team", UpdateDetail_Team_name, UpdateDetail_Team_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Timeline service

type TimelineClient interface {
	GetTimelineData(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*TimelineReport, error)
}

type timelineClient struct {
	cc *grpc.ClientConn
}

func NewTimelineClient(cc *grpc.ClientConn) TimelineClient {
	return &timelineClient{cc}
}

func (c *timelineClient) GetTimelineData(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*TimelineReport, error) {
	out := new(TimelineReport)
	err := grpc.Invoke(ctx, "/timeline.Timeline/GetTimelineData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timeline service

type TimelineServer interface {
	GetTimelineData(context.Context, *TimelineRequest) (*TimelineReport, error)
}

func RegisterTimelineServer(s *grpc.Server, srv TimelineServer) {
	s.RegisterService(&_Timeline_serviceDesc, srv)
}

func _Timeline_GetTimelineData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServer).GetTimelineData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeline.Timeline/GetTimelineData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServer).GetTimelineData(ctx, req.(*TimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timeline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timeline.Timeline",
	HandlerType: (*TimelineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimelineData",
			Handler:    _Timeline_GetTimelineData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("timeline.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 895 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0x63, 0xcb, 0x91, 0x8e, 0x63, 0x5b, 0xe1, 0xba, 0x41, 0x75, 0x07, 0x34, 0xf0, 0x7e,
	0x50, 0x74, 0x83, 0x33, 0x64, 0x03, 0x06, 0x0c, 0xbb, 0xe9, 0xda, 0xb4, 0x0d, 0xd6, 0x34, 0x06,
	0xe3, 0x5d, 0xf4, 0x6a, 0xa0, 0x2d, 0xda, 0x11, 0x2a, 0x4b, 0x9e, 0x44, 0xad, 0xf0, 0x33, 0xec,
	0x1d, 0x76, 0xbf, 0xc7, 0xd9, 0x9b, 0xec, 0x11, 0xc6, 0x73, 0x28, 0x59, 0xf2, 0xdf, 0x96, 0xa0,
	0x37, 0x09, 0xf9, 0x9d, 0x8f, 0xe4, 0xe1, 0xf9, 0x3e, 0x1d, 0x1a, 0x3a, 0x2a, 0x98, 0xcb, 0x30,
	0x88, 0xe4, 0x60, 0x91, 0xc4, 0x2a, 0x66, 0x76, 0x31, 0xef, 0x3d, 0x9a, 0xc5, 0xf1, 0x2c, 0x94,
	0xa7, 0x84, 0x8f, 0xb3, 0xe9, 0x29, 0x46, 0x52, 0x25, 0xe6, 0x0b, 0x43, 0xed, 0x7f, 0x05, 0xdd,
	0x51, 0x4e, 0xe6, 0xf2, 0xb7, 0x4c, 0xc7, 0x98, 0x07, 0x87, 0xf2, 0x77, 0x19, 0xa9, 0x0b, 0xdf,
	0xab, 0x9d, 0xd4, 0x1e, 0x37, 0x78, 0x31, 0xed, 0xff, 0x53, 0x87, 0x4e, 0xc9, 0x5e, 0xc4, 0x89,
	0x62, 0x27, 0xd0, 0xa2, 0xe8, 0x68, 0xb9, 0x90, 0xf9, 0x82, 0x36, 0xaf, 0x42, 0xd5, 0xed, 0x0e,
	0xd6, 0xb6, 0x63, 0x5f, 0x80, 0x95, 0x4e, 0xe2, 0x44, 0x7a, 0x75, 0x8d, 0xb7, 0xce, 0xba, 0x83,
	0xd5, 0x35, 0xae, 0x11, 0xe6, 0x26, 0x8a, 0x47, 0x60, 0xe0, 0x3c, 0x14, 0x8b, 0x54, 0xfa, 0x5e,
	0x43, 0x93, 0x2d, 0x5e, 0x85, 0xd8, 0x00, 0x98, 0x34, 0x43, 0x2e, 0x67, 0x59, 0x28, 0x12, 0x4c,
	0xd2, 0xb3, 0x88, 0xb8, 0x23, 0xc2, 0x7e, 0x84, 0x76, 0xb6, 0xf0, 0x85, 0x92, 0xcf, 0xa5, 0x12,
	0x41, 0x98, 0x7a, 0xcd, 0x93, 0xba, 0x4e, 0xe0, 0x93, 0x32, 0x81, 0x5f, 0x2a, 0x61, 0xbe, 0x4e,
	0x66, 0xdf, 0x43, 0x53, 0x57, 0x50, 0x65, 0xa9, 0x77, 0xa8, 0x4f, 0xe8, 0x9c, 0x3d, 0x2a, 0x97,
	0xad, 0x17, 0x67, 0x70, 0x4d, 0x34, 0x9e, 0xd3, 0xd9, 0x4f, 0x70, 0x1c, 0x44, 0xc3, 0x50, 0x2c,
	0x2f, 0x85, 0x9a, 0xdc, 0x98, 0xa0, 0x67, 0xd3, 0x1e, 0xf7, 0x37, 0x8f, 0xc6, 0xe2, 0xf1, 0x6d,
	0x7a, 0xef, 0x02, 0xba, 0x2f, 0xb2, 0x30, 0x1c, 0x55, 0x6e, 0xcf, 0xa0, 0x71, 0x13, 0x67, 0x09,
	0xd5, 0xde, 0xe2, 0x34, 0x66, 0x2e, 0xd4, 0xe7, 0x41, 0x44, 0x05, 0xb7, 0x38, 0x0e, 0x11, 0x49,
	0xe5, 0x84, 0x4a, 0xad, 0x11, 0x3d, 0xec, 0x7f, 0x06, 0x4d, 0xb3, 0x29, 0x6b, 0xc1, 0xe1, 0xc5,
	0x9b, 0x5f, 0x87, 0xaf, 0x9f, 0xbe, 0x75, 0xef, 0xb1, 0x23, 0xb0, 0x9f, 0x5d, 0x5d, 0x0e, 0x5f,
	0x9f, 0x8f, 0xce, 0xdd, 0x5a, 0xff, 0xaf, 0x3a, 0x1c, 0x55, 0x8b, 0xc1, 0x7e, 0x00, 0x30, 0xe5,
	0xa0, 0x1a, 0xd7, 0x48, 0xb9, 0xde, 0xc0, 0xd8, 0x6c, 0x50, 0xd8, 0x8c, 0x0a, 0x41, 0x36, 0xe3,
	0x15, 0x36, 0xeb, 0x81, 0x6d, 0x66, 0xb9, 0x17, 0x2c, 0xbe, 0x9a, 0xb3, 0x53, 0x68, 0x28, 0x29,
	0xe6, 0x94, 0x60, 0xe7, 0xec, 0xe1, 0x6e, 0x29, 0x06, 0x23, 0x4d, 0xe1, 0x44, 0xc4, 0xcd, 0xf0,
	0xff, 0x1b, 0xa1, 0xd3, 0x40, 0x4f, 0x38, 0x7c, 0x35, 0x67, 0x9f, 0x82, 0x33, 0xc7, 0xa2, 0x55,
	0x7c, 0x50, 0x02, 0x7b, 0xec, 0xd2, 0xdc, 0x6b, 0x97, 0xc7, 0x3a, 0x35, 0x2d, 0x47, 0x2e, 0xf7,
	0x6e, 0xa9, 0x88, 0xc1, 0xbe, 0x5b, 0x15, 0x07, 0xf9, 0xff, 0x25, 0x6d, 0x85, 0xc7, 0x9e, 0x80,
	0x9b, 0x9f, 0xfa, 0xd4, 0xf7, 0xa5, 0x4f, 0xd9, 0x38, 0x94, 0xcd, 0x16, 0xde, 0xef, 0x41, 0x03,
	0x6b, 0xc0, 0x6c, 0x14, 0x7d, 0x2e, 0xb5, 0x5e, 0x7a, 0x24, 0xde, 0x8b, 0xa5, 0xd6, 0xea, 0x0f,
	0x1b, 0x2c, 0xfa, 0x72, 0xb0, 0x98, 0x18, 0xcd, 0xe5, 0x79, 0xb8, 0xf1, 0x61, 0x99, 0xbf, 0xb9,
	0xb9, 0x89, 0x88, 0x0b, 0x70, 0x13, 0x52, 0xe5, 0xff, 0x16, 0x20, 0x91, 0x7d, 0x03, 0x1f, 0x45,
	0xd9, 0x7c, 0x2c, 0x93, 0xab, 0xe9, 0x5b, 0x19, 0x86, 0xf1, 0xfb, 0x67, 0x22, 0xf1, 0xd3, 0xdc,
	0x5e, 0xbb, 0x42, 0x78, 0xcb, 0x02, 0xe6, 0xd2, 0x37, 0x74, 0xf3, 0x2d, 0x6f, 0xe1, 0xec, 0x73,
	0x68, 0x17, 0x98, 0x21, 0x1a, 0x0d, 0xd7, 0x41, 0xad, 0x4b, 0x77, 0x05, 0xc4, 0x49, 0x24, 0x93,
	0x34, 0x17, 0x71, 0x13, 0xd6, 0xa6, 0xf5, 0x36, 0xa0, 0x17, 0x41, 0x92, 0xaa, 0x57, 0x22, 0x9c,
	0x92, 0xaa, 0x16, 0xdf, 0x1b, 0xd7, 0xcd, 0xe2, 0xc1, 0x46, 0xec, 0x5a, 0x4e, 0xe2, 0xc8, 0xa7,
	0xc5, 0x36, 0x2d, 0xde, 0x4f, 0xc0, 0x9b, 0x8c, 0xe3, 0xf8, 0x5d, 0x10, 0xcd, 0x86, 0x71, 0x10,
	0xa9, 0x34, 0x17, 0x76, 0x1d, 0xec, 0xfd, 0xdd, 0x80, 0x56, 0xa5, 0xc6, 0xf8, 0x49, 0x47, 0x22,
	0xd7, 0xcf, 0xe1, 0x34, 0x66, 0xf7, 0x8b, 0x6e, 0x79, 0x40, 0x60, 0xde, 0x1c, 0xf5, 0xfe, 0x37,
	0xfa, 0x1c, 0xf4, 0xc6, 0xf5, 0xaa, 0x97, 0x3a, 0x7c, 0x1d, 0x44, 0xd6, 0x34, 0xef, 0x1a, 0x86,
	0x65, 0x3e, 0x98, 0x75, 0x90, 0x7d, 0x09, 0x9d, 0x85, 0x8c, 0x44, 0xa8, 0x02, 0x99, 0x1a, 0x9a,
	0x45, 0xb4, 0x0d, 0x94, 0x7d, 0x0d, 0xc7, 0x25, 0x82, 0x8f, 0x46, 0x34, 0x91, 0xd4, 0x42, 0x1d,
	0xbe, 0x1d, 0xc0, 0xbc, 0x67, 0x3a, 0x7f, 0xd3, 0x2d, 0x75, 0xde, 0x34, 0xc1, 0x1b, 0xa6, 0x52,
	0x99, 0xf6, 0xa7, 0x6f, 0x88, 0xe3, 0x7d, 0x9e, 0x72, 0xee, 0xe6, 0x29, 0xb8, 0xad, 0xa7, 0x5a,
	0xb7, 0xf4, 0xd4, 0xd1, 0xdd, 0x3d, 0xd5, 0xfe, 0x10, 0x4f, 0x75, 0xee, 0xec, 0xa9, 0xee, 0x0e,
	0x4f, 0x3d, 0xf9, 0xb3, 0x06, 0x50, 0x36, 0x1c, 0xec, 0xf1, 0x3f, 0x07, 0x93, 0x77, 0x57, 0xd3,
	0xa9, 0xe9, 0x19, 0x2f, 0x63, 0x11, 0xba, 0x35, 0xd6, 0x01, 0x28, 0x0b, 0xea, 0x1e, 0x20, 0x2d,
	0xaf, 0x98, 0x5b, 0xd7, 0x6f, 0xc6, 0xd1, 0x2a, 0xe7, 0xf3, 0xc8, 0x77, 0x1b, 0xec, 0x18, 0xda,
	0x65, 0x22, 0x08, 0x59, 0xec, 0x63, 0x38, 0x2e, 0xa1, 0xe2, 0x88, 0x26, 0x32, 0x2f, 0x83, 0x54,
	0xf7, 0xae, 0x21, 0x39, 0x62, 0xe9, 0x1e, 0xb2, 0x36, 0x38, 0xc3, 0xc2, 0x1e, 0xae, 0x7d, 0x36,
	0x02, 0xbb, 0x78, 0x2f, 0xd9, 0x2b, 0xe8, 0xbe, 0x94, 0xaa, 0x98, 0x3e, 0x17, 0x4a, 0xb0, 0x07,
	0xbb, 0x9e, 0x55, 0xfa, 0x85, 0xd2, 0xf3, 0xf6, 0xbd, 0xb8, 0xfd, 0x7b, 0xe3, 0x26, 0xbd, 0x41,
	0xdf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xae, 0x48, 0xe7, 0x60, 0x14, 0x09, 0x00, 0x00,
}
